# Build
source:       html
destination:  dist

# Encoding
encoding: utf-8

# Server
port:     4000
host:     127.0.0.1
baseurl:  ""
url:      ""

# Permalinks
permalink:  pretty

# Site settings
title: GitHub Pages boilerplate
tagline: Starter repository for GitHub Pages workflow with Grunt.
description:
author: Cătălin Dogaru
